bundle:
  groupId: "io.jenkins.tools.custom-war-packager.demo.casc"
  artifactId: "jenkins-casc-demo"
  vendor: "Jenkins project"
  title: "Configuration-as-Code demo"
  description: "Configuration-as-Code demo, produced by Custom WAR Packager"
buildSettings:
  pom: foo.xml
  docker:
    base: "jenkins/jenkins:2.138.2"
    tag: "jenkins-experimental/custom-war-packager-casc-demo"
    build: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: 2.138.2
systemProperties:
  jenkins.install.runSetupWizard: "false"
  jenkins.model.Jenkins.slaveAgentPort: "50000"
  jenkins.model.Jenkins.slaveAgentPortEnforce: "true"
casc:
  - id: "casc"
    source:
      dir: casc.yml
